### ISSUE TITLE
error in make

### ISSUE THREAD

**Issue by Zibri** [openpst/openpst#3]
if [ ! -d "./libopenpst/include" ] || [ ! -d "./gui-common/include" ]; then git submodule init && git submodule update;  fi
Submodule 'gui-common' (https://github.com/openpst/gui-common) registered for path 'gui-common'
Submodule 'libopenpst' (https://github.com/openpst/libopenpst) registered for path 'libopenpst'
Submodule 'qcdm' (https://github.com/openpst/qcdm) registered for path 'qcdm'
Submodule 'readmbn' (https://github.com/openpst/readmbn) registered for path 'readmbn'
Submodule 'sahara' (https://github.com/openpst/sahara) registered for path 'sahara'
Submodule 'streaming-dload' (https://github.com/openpst/streaming-dload) registered for path 'streaming-dload'
Cloning into '/home/zibri/openpst/gui-common'...
Cloning into '/home/zibri/openpst/libopenpst'...
Cloning into '/home/zibri/openpst/qcdm'...
Cloning into '/home/zibri/openpst/readmbn'...
Cloning into '/home/zibri/openpst/sahara'...
Cloning into '/home/zibri/openpst/streaming-dload'...
Submodule path 'gui-common': checked out 'f794e7f41deda95989010ad5be1b09f3e729b5af'
Submodule path 'libopenpst': checked out '2153903f6662d017a5a855c36b82ced95207a0ca'
Submodule path 'qcdm': checked out 'e080246d630e57ebf41d573483733a3d3bc94ab3'
Submodule path 'readmbn': checked out '774abb5e2cb8d8cbbab3255e8aee28ece7208151'
Submodule path 'sahara': checked out '2111b9101a449f65b28935e5e155d76c98de1f4f'
Submodule path 'streaming-dload': checked out '99d9d745a6237bde26c4c51c1f25da67ea2b9241'
if [ ! -d "./libopenpst/lib/serial/include" ]; then cd ./libopenpst/ && git submodule init && git submodule update;  fi
Submodule 'lib/pugixml' (https://github.com/zeux/pugixml) registered for path 'lib/pugixml'
Submodule 'serial' (https://github.com/wjwwood/serial.git) registered for path 'lib/serial'
Cloning into '/home/zibri/openpst/libopenpst/lib/pugixml'...
Cloning into '/home/zibri/openpst/libopenpst/lib/serial'...
Submodule path 'lib/pugixml': checked out '03e4b8de929328eb5cbb031ff535c50396d43bb9'
Submodule path 'lib/serial': checked out '827c4a784dd4fdd35dc391f37ef152eab7c9c9b2'
qmake -makefile -o ./build/Makefile openpst.pro 
qmake: could not exec '/usr/lib/x86_64-linux-gnu/qt4/bin/qmake': No such file or directory
Makefile:8: recipe for target 'openpst' failed
make: *** [openpst] Error 1

**Comment by ghassani** [comment]
Looks like you have an issue with your QT install, also QT 5 is required not QT4.

Also this repo isnt building right now. You can build seperately libopenpst, sahara, streaming-dload, and readmbn from their respective repositories

**Comment by ghassani** [comment]
Closing
