### ISSUE TITLE
Master compile error

### ISSUE THREAD

**Issue by Zibri** [openpst/openpst#4]
In file included from ../../sahara/include/sahara_window.h:37:0,
                 from ../../sahara/src/sahara_window.cpp:28:
./ui_sahara_window.h:32:10: fatal error: widget/log_widget.h: No such file or directory
 #include "widget/log_widget.h"
          ^~~~~~~~~~~~~~~~~~~~~
compilation terminated.
Makefile:401: recipe for target 'sahara_window.o' failed
make[2]: *** [sahara_window.o] Error 1
make[2]: Leaving directory '/home/zibri/testfs/openpst/build/sahara'
Makefile:91: recipe for target 'sub-sahara-sahara-pro-make_first-ordered' failed
make[1]: *** [sub-sahara-sahara-pro-make_first-ordered] Error 2
make[1]: Leaving directory '/home/zibri/testfs/openpst/build'
Makefile:8: recipe for target 'openpst' failed
make: *** [openpst] Error 2

**Comment by ghassani** [comment]
See https://github.com/openpst/openpst/issues/1
